name: ascii-videoplayer # you probably want to 'snapcraft register <name>'
version: '1r'
summary: Low resolution(spatial and color) video player/image render for terminal
description: 
  An overly simple videoplayer using opencv and ncurses library for terminal. Currently only pause and quitting feature is implemented.
  Tested for ubuntu 18(bionic), should work for 20 also. Tested image and video formats are .jpg, .png, .tif, .mp4

  To run give command ascii_player <image/video name>

  Press 'q' to quit and 'p' to pause.
  

# https://snapcraft.io/docs/base-snaps
# by default, base is defined as core whic use xenial packages of which opencv package is different 
# so core18 (bionic) it is
base: core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

# cmd to run the application
apps:
  ascii-videoplayer:
    command: ascii-videoplayer

parts:
  ascii-videoplayer:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/Jaiaid/ascii_videoplayer.git
    source-branch: main
    build-packages: [g++, pkg-config, libncursesw5-dev, libopencv-core-dev, libopencv-imgproc-dev, libopencv-imgcodecs-dev, libopencv-video-dev]
    stage-packages: [libncursesw5, libopencv-core3.2, libopencv-imgproc3.2, libopencv-imgcodecs3.2, libopencv-videoio3.2, libopenblas-base]
    after:
      - ffmpeg-avcodec56

  # needed for libavcodec56, which is not available in core18
  # so needs building from source
  ffmpeg-avcodec56:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/FFmpeg/FFmpeg.git
    source-branch: release/2.8
    configflags:
      - --disable-static
      - --enable-shared
      - --enable-pic
      - --disable-programs
      - --disable-ffplay
      - --disable-ffprobe
      - --disable-ffserver
      - --disable-avdevice
      - --disable-postproc
      - --disable-avfilter
      - --disable-network
      - --disable-dct
      - --disable-dwt
      - --disable-lsp
      - --disable-lzo
      - --disable-mdct
      - --disable-rdft
      - --disable-fft
      - --disable-faan
      - --disable-pixelutils
      - --disable-yasm
    build-packages: [g++, make]
    override-build: |
      # first do the actual build
      snapcraftctl build
      # then do other intended work
      # You're in the build dir now. We're essentially
      # writing install rules in shell.
      mkdir -p $SNAPCRAFT_PRIME/lib/
      cp -r $SNAPCRAFT_PART_INSTALL/usr/local/lib/* $SNAPCRAFT_PRIME/lib/
      # pushd $SNAPCRAFT_PRIME
      cp $SNAPCRAFT_PART_INSTALL/usr/local/lib/libavcodec.so.56 $SNAPCRAFT_PRIME/lib/libavcodec-ffmpeg.so.56
      cp $SNAPCRAFT_PART_INSTALL/usr/local/lib/libavformat.so.56 $SNAPCRAFT_PRIME/lib/libavformat-ffmpeg.so.56
      cp $SNAPCRAFT_PART_INSTALL/usr/local/lib/libavutil.so.54 $SNAPCRAFT_PRIME/lib/libavutil-ffmpeg.so.54
      cp $SNAPCRAFT_PART_INSTALL/usr/local/lib/libswscale.so.3 $SNAPCRAFT_PRIME/lib/libswscale-ffmpeg.so.3
      # popd
