name: ascii-videoplayer # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

# https://snapcraft.io/docs/base-snaps
# by default, base is defined as core whic use xenial packages of which opencv package is different 
# so core18 (bionic) it is
base: core18
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ascii-videoplayer:
    # See 'snapcraft plugins'
    plugin: make
    source: https://github.com/Jaiaid/ascii_videoplayer.git
    source-branch: beta
    build-packages: [g++, pkg-config, libncursesw5-dev, libopencv-core-dev, libopencv-imgproc-dev, libopencv-videoio-dev]
    stage-packages: [libncursesw5, libopencv-core, libopencv-imgproc, libopencv-videoio]
